In [27]:
#demo different programing elements
#
import os
# Current working directory
notebook_directory = os.getcwd()
print(f"The notebook is running in: {notebook_directory}")

The notebook is running in: /Users/enriquecaballero/Documents/Python


In [29]:
numbers = list(range(1,10))
print(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
for z in range(0, 9):
    print(z, numbers[z] + 0.5)

0 1.5
1 2.5
2 3.5
3 4.5
4 5.5
5 6.5
6 7.5
7 8.5
8 9.5


In [33]:
for z in range(10, 20):
    print(z, z + 0.5)

10 10.5
11 11.5
12 12.5
13 13.5
14 14.5
15 15.5
16 16.5
17 17.5
18 18.5
19 19.5


In [43]:
# Declare an empty list
w = list()
print(w)
j = 0
for z in range(10, 20):
# Append to list as needed
    w.append(z + 0.5)
    print(j)
    j = j + 1
print(w)
print(j)

[]
0
1
2
3
4
5
6
7
8
9
[10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5]
10


In [45]:
stockp = 100
K = 100
if stockp > K:
    print("Option is in the money")
else:
    print("Option is out of the money")

Option is out of the money


In [47]:
stockp = 100
K = 100
if stockp > K:
    print("Option is in-the-money")
elif stockp == K:
    print("Option is at-the-money")
else:
    print("Option is out-of-the-money")

Option is at-the-money


In [51]:
# This module illustrates different ways to create 2-dimensional arrays pre-populated with zeros or ones or numbersimport numpy as np
import numpy as np
carray = np.arange(0, 20).reshape(4, 5)
carray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
czeros = np.zeros((3, 3))
print("Printing the array filled with zeros")
print(czeros)
print()
print("Printing the array filled with ones")
cones = np.ones((3, 3))
print(cones)

Printing the array filled with zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Printing the array filled with ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
# Add two matrices
A = np.array([[2, 4], [5, -6]])
print("A", A)
B = np.array([[9, -3], [3, 6]])
print("B", B)

# Element-wise addition
C = A + B
print("C", C)

# Element-wise multiplication
D = A * B
print("D", D)

# Dot product
E = A.dot(B)
print("E", E)

A [[ 2  4]
 [ 5 -6]]
B [[ 9 -3]
 [ 3  6]]
C [[11  1]
 [ 8  0]]
D [[ 18 -12]
 [ 15 -36]]
E [[ 30  18]
 [ 27 -51]]


In [61]:
m = np.array([1, 2, 3, 4])
n = np.array([4, 2, 2, 4])
print(m == n)
print(m > n)

[False  True False  True]
[False False  True False]


In [63]:
# Panda Data Frames
import pandas as pd

df = pd.DataFrame(
        {"a": [1, 2, 3],
        "b": [4, 5, 6],
        "c": [7, 8, 9]},
    index=[1, 2, 3])
df

a  b  c
1  1  4  7
2  2  5  8
3  3  6  9

In [65]:
print(sum(df.c))
print(sum(df.loc[3]))

24
18
